// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import config "github.com/yadavparmatma/git_master/config"
import mock "github.com/stretchr/testify/mock"
import model "github.com/yadavparmatma/git_master/model"
import sync "sync"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CreateUrl provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Client) CreateUrl(_a0 *config.Config, _a1 string, _a2 chan string, _a3 *sync.WaitGroup) {
	_m.Called(_a0, _a1, _a2, _a3)
}

// Fetch provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) Fetch(_a0 string, _a1 chan []model.Repo, _a2 *sync.WaitGroup) {
	_m.Called(_a0, _a1, _a2)
}
