// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import config "github.com/yadavparmatma/git_master/config"
import mock "github.com/stretchr/testify/mock"
import model "github.com/yadavparmatma/git_master/model"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CreateUrl provides a mock function with given fields: _a0, _a1
func (_m *Client) CreateUrl(_a0 *config.Config, _a1 string) string {
	ret := _m.Called(_a0, _a1)

	var r0 string
	if rf, ok := ret.Get(0).(func(*config.Config, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Fetch provides a mock function with given fields: _a0
func (_m *Client) Fetch(_a0 string) []model.Repo {
	ret := _m.Called(_a0)

	var r0 []model.Repo
	if rf, ok := ret.Get(0).(func(string) []model.Repo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Repo)
		}
	}

	return r0
}
