// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/yadavparmatma/git_master/model"

// Printer is an autogenerated mock type for the Printer type
type Printer struct {
	mock.Mock
}

// Print provides a mock function with given fields: _a0
func (_m *Printer) Print(_a0 []model.Repo) {
	_m.Called(_a0)
}
