// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/yadavparmatma/git_master/model"

// TaskExecutor is an autogenerated mock type for the TaskExecutor type
type TaskExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *TaskExecutor) Execute(_a0 string) chan []model.Repo {
	ret := _m.Called(_a0)

	var r0 chan []model.Repo
	if rf, ok := ret.Get(0).(func(string) chan []model.Repo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan []model.Repo)
		}
	}

	return r0
}
